### ISSUE TITLE
SIM-CI-Image tags are not being pushed with semver

### ISSUE THREAD

**Issue by AgustinRamiroDiaz** [yeagerai/genlayer-studio#601]
Image tags are being published each day, but only with `latest` tag and not with the semver tag they correspond to

https://hub.docker.com/r/yeagerai/simulator-jsonrpc/tags
![image](https://github.com/user-attachments/assets/b1a32a08-4e4a-4e04-8ffe-5ed25546bdfe)

**Comment by YeagerAI-Bulat** [comment]
@mentatbot
