### ISSUE TITLE
Reset storage button confusion

### ISSUE THREAD

**Issue by kstroobants** [yeagerai/genlayer-studio#616]
Reset storage button in settings only restores the example contracts but not the ones made by the user. 
- Do we want the same functionality for the user generated intelligent contracts?
- Does it resets the browser cache?
- The button does not reset the database for listed contracts. Why not?

"All the examples will be restored" vs "following intelligent contracts will be removed". After pressing the button the contract files are still there.

![Screenshot 2024-11-18 at 21 29 28](https://github.com/user-attachments/assets/14fc1d35-23ff-4102-94fe-b6cd5f91e278)

**Comment by denishacquin** [comment]
Comments from edgars and cristiam:
Yes, clear out everything, it should give you a clean slate - it helps in case something gets messed up in the storage, which can happen during many breaking changes
ok, lets reset everything but please 
 lets be sure that the message is clear and suggest a backup of the contracts they don't want to loose
